version: '3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer-1
    command: -H unix:///var/run/docker.sock
    ports:
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      qnet-static:
        ipv4_address: 192.168.251.52
    restart: always
volumes:
  portainer_data:
# here the network driver is configured.
networks:
  qnet-static:
    driver: qnet
    driver_opts:
      iface: "eth4"
    ipam:
      driver: qnet
      options:
        iface: "eth4"
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.192.1