version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /share/CACHEDEV1_DATA/docker/nginx-pm/data:/data
      - /share/CACHEDEV1_DATA/docker/nginx-pm/letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true
    restart: on-failure
    networks:
      - qnet-dhcp
networks:
  qnet-dhcp:
    driver: qnet
    driver_opts:
      iface: "eth4"
    ipam:
      driver: qnet
      options:
        iface: "eth4"