version: "3"

volumes:
  bindplane:
  prometheus:

services:
  prometheus:
    container_name: bindplane-prometheus
    restart: always
    image: ghcr.io/observiq/bindplane-prometheus:1.48.0
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
    networks:
     qnet-static:
      ipv4_address: 192.168.251.54

  transform:
    container_name: bindplane-transform-agent
    restart: always
    image: ghcr.io/observiq/bindplane-transform-agent:latest
    ports:
      - "4568:4568"
    networks:
     qnet-static:
      ipv4_address: 192.168.251.55

  bindplane:
    container_name: bindplane-server
    restart: always
    image: ghcr.io/observiq/bindplane-ee:1.48.0
    ports:
      - "3001:3001"
    networks:
     qnet-static:
      ipv4_address: 192.168.251.56
    environment:
      - BINDPLANE_USERNAME=admin
      - BINDPLANE_PASSWORD=Washhouse-Twitch0-Unaudited-Grudging
      - BINDPLANE_REMOTE_URL=http://192.168.251.56:3001
      - BINDPLANE_SESSION_SECRET=E13B6253-756A-4F12-B2FD-C7A5C709330C
      - BINDPLANE_SECRET_KEY=F6FB3FD9-4729-4814-9130-E474EA54448E
      - BINDPLANE_LOG_OUTPUT=stdout
      - BINDPLANE_ACCEPT_EULA=true
      - BINDPLANE_PROMETHEUS_ENABLE=true
      - BINDPLANE_PROMETHEUS_ENABLE_REMOTE=true
      - BINDPLANE_PROMETHEUS_HOST=prometheus
      - BINDPLANE_PROMETHEUS_PORT=9090
      - BINDPLANE_TRANSFORM_AGENT_ENABLE_REMOTE=true
      - BINDPLANE_TRANSFORM_AGENT_REMOTE_AGENTS=transform:4568
    volumes:
      - bindplane:/data
    depends_on:
      - prometheus
      - transform
# here the network driver is configured.
networks:
  qnet-static:
    external: true