version: "3"
services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=Promoter9-Arrange-Private
    restart: always
    networks:
      qnet-static:
        ipv4_address: 192.168.251.53
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=Promoter9-Arrange-Private
      - POSTGRES_DB=gitea
    networks:
      qnet-static:
        ipv4_address: 192.168.251.54
    volumes:
      - ./postgres:/var/lib/postgresql/data
networks:
  qnet-static:
    external: true