version: "3.4"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    networks:
      qnet-static:
        ipv4_address: 192.168.251.30
networks:
  qnet-static:
    external: true