version: '3' # Specify Docker Compose file version

services:
  prometheus:
    container_name: monitoring-prometheus
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - monitoring_prometheus_data:/prometheus
    restart: unless-stopped
    networks:
     qnet-static:
      ipv4_address: 192.168.251.57      
  
  grafana:
    image: grafana/grafana:latest  # Use latest Grafana image
    container_name: monitoring-grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      #- ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      #- ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      #- monitoring_grafana_data:/var/lib/grafana # Volume for Grafana data
    ports:
      - 3000:3000  # Expose Grafana port 3000
    restart: unless-stopped
    networks:
     qnet-static:
      ipv4_address: 192.168.251.58
    depends_on:
      - prometheus  # Grafana depends on the Prometheus service

volumes:
  monitoring_prometheus_data:
    driver: local  # Named volume for Prometheus
  #monitoring_grafana_data:  
   # driver: local   # Named volume for Grafana

networks:
  qnet-static:
    external: true