version: '3' # Specify Docker Compose file version

services:
  prometheus:
    image: prom/prometheus:latest  # Use latest Prometheus image
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount configuration file
      - monitoring_prometheus_data:/prometheus  # Volume for Prometheus data
    ports:
      - 9090:9090  # Expose Prometheus port 9090
    networks:
     qnet-static:
      ipv4_address: 192.168.251.57      

  grafana:
    image: grafana/grafana:latest  # Use latest Grafana image
    container_name: monitoring-grafana
    volumes:
      - monitoring_grafana_data:/var/lib/grafana # Volume for Grafana data
    ports:
      - 3000:3000  # Expose Grafana port 3000
    networks:
     qnet-static:
      ipv4_address: 192.168.251.58
    depends_on:
      - prometheus  # Grafana depends on the Prometheus service

volumes:
  monitoring_prometheus_data:  # Named volume for Prometheus
  monitoring_grafana_data:     # Named volume for Grafana