version: '3' # Specify Docker Compose file version

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    restart: unless-stopped
    container_name: prometheus
    networks:
     qnet-static:
      ipv4_address: 192.168.251.57      
  
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
     qnet-static:
      ipv4_address: 192.168.251.58
    depends_on:
      - prometheus  # Grafana depends on the Prometheus service
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
     qnet-static:
      ipv4_address: 192.168.251.59
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave    
    networks:
     qnet-static:
      ipv4_address: 192.168.251.63
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  qnet-static:
    external: true