---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks/

# /////////////////////////////////////// HOME TAB

- ㅤ:
    - Youtube:
        - abbr: YT
          href: https://youtube.com/
    - ChatGPT:
        - abbr: GPT
          href: https://chat.openai.com/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - Gmail:
        - abbr: GM
          href: https://gmail.com/

- Shopping:
    - Amazon:
        - abbr: AMZ
          href: https://amazon.ca/

- Development:
    - Github:
        - abbr: GH
          href: https://github.com/

# /////////////////////////////////////// MEDIA & DOWNLOADS TAB


- ㅤㅤ:
    - Seedbox:
        - abbr: US
          href: https://seedbox.com/
    - Seedbox qBittorrent:
        - abbr: QBIT
          href: https://seedbox.com/qbit
    - Seedbox Autobrr:
        - abbr: ABR
          href: https://seedbox.com/autobrr
    - Local Autobrr:
        - abbr: ABR
          href: https://example.local/autobrr
- Private Trackers:
    - 👀:
        - abbr: "??"
          href: https://fillmeout.com
- Public Trackers:
    - RARBG ・ Public General:
        - abbr: RAR
          href: https://therarbg.to/
    - 1337x ・ Public General:
        - abbr: LT
          href: https://1337x.to/
    - Nyaa ・ Public Anime:
        - abbr: AB
          href: https://nyaa.si/

# /////////////////////////////////////// MANAGEMENT TAB

- ㅤㅤㅤ:
    - Server Setup Spreadsheet:
        - abbr: SSS
          href: https://spreadsheet.com
    - Server Diagram:
        - abbr: SD
          href: https://diagram.com

- Documentation:
    - Homepage:
        - abbr: HP
          href: https://gethomepage.dev/