global:
  scrape_interval: 60s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 60s # How frequently to evaluate rules.

# A scrape configuration
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 

  - job_name: 'linux_servers'
    static_configs:
      - targets: 
        - '192.168.251.221:9100' 
        - '192.168.255.219:9100'
        # ... more Linux servers
  - job_name: 'windows_servers'
    static_configs:
      - targets: 
        - 'windows_node_1:9182' 
        - 'windows_node_2:9182'
        # ... more Windows servers